//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 客户管理系统.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRMEntities : DbContext
    {
        public CRMEntities()
            : base("name=CRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Floors> Floors { get; set; }
        public virtual DbSet<Houses> Houses { get; set; }
        public virtual DbSet<OperationLogs> OperationLogs { get; set; }
        public virtual DbSet<Provinces> Provinces { get; set; }
        public virtual DbSet<RoomCategories> RoomCategories { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<SchoolClasses> SchoolClasses { get; set; }
        public virtual DbSet<Schools> Schools { get; set; }
        public virtual DbSet<SelectStationPeriods> SelectStationPeriods { get; set; }
        public virtual DbSet<Specialties> Specialties { get; set; }
        public virtual DbSet<Stations> Stations { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
        public virtual DbSet<TrainClasses> TrainClasses { get; set; }
        public virtual DbSet<TrainClassRooms> TrainClassRooms { get; set; }
        public virtual DbSet<View_ChooseJobs> View_ChooseJobs { get; set; }
        public virtual DbSet<View_TrainClasses> View_TrainClasses { get; set; }
        public virtual DbSet<TrainClassTeachers> TrainClassTeachers { get; set; }
        public virtual DbSet<View_SchoolS> View_SchoolS { get; set; }
        public virtual DbSet<View_Stations> View_Stations { get; set; }
        public virtual DbSet<SpecialtyStations> SpecialtyStations { get; set; }
        public virtual DbSet<View_TrainTeachers> View_TrainTeachers { get; set; }
        public virtual DbSet<View_Students> View_Students { get; set; }
        public virtual DbSet<TrainClassStudents> TrainClassStudents { get; set; }
    }
}
