//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 客户管理系统.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationLogs
    {
        public int PL_ID { get; set; }
        public Nullable<int> T_ID { get; set; }
        public string PL_TableName { get; set; }
        public string PL_Operation { get; set; }
        public string PL_Description { get; set; }
        public Nullable<System.DateTime> PL_Time { get; set; }
    
        public virtual Teachers Teachers { get; set; }
    }
}
