//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 客户管理系统.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rooms()
        {
            this.TrainClassRooms = new HashSet<TrainClassRooms>();
            this.TrainClassStudents = new HashSet<TrainClassStudents>();
        }
    
        public int R_ID { get; set; }
        public Nullable<int> F_ID { get; set; }
        public Nullable<int> RC_ID { get; set; }
        public string R_Name { get; set; }
        public Nullable<byte> R_MaleOrFemale { get; set; }
        public Nullable<bool> R_IsHasFull { get; set; }
    
        public virtual Floors Floors { get; set; }
        public virtual RoomCategories RoomCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainClassRooms> TrainClassRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainClassStudents> TrainClassStudents { get; set; }
    }
}
