//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 客户管理系统.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schools
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schools()
        {
            this.SchoolClasses = new HashSet<SchoolClasses>();
            this.SelectStationPeriods = new HashSet<SelectStationPeriods>();
        }
    
        public int School_ID { get; set; }
        public Nullable<int> P_ID { get; set; }
        public string School_Code { get; set; }
        public string School_Name { get; set; }
        public string School_Remark { get; set; }
    
        public virtual Provinces Provinces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolClasses> SchoolClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelectStationPeriods> SelectStationPeriods { get; set; }
    }
}
