//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 客户管理系统.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectStationPeriods
    {
        public int SSP_ID { get; set; }
        public Nullable<int> School_ID { get; set; }
        public Nullable<int> Specialty_ID { get; set; }
        public System.DateTime SSP_PreachDate { get; set; }
        public byte SSP_OverDay { get; set; }
    
        public virtual Schools Schools { get; set; }
        public virtual Specialties Specialties { get; set; }
    }
}
