//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 客户管理系统.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int Student_ID { get; set; }
        public Nullable<int> SC_ID { get; set; }
        public string Student_NO { get; set; }
        public string Student_Name { get; set; }
        public string Student_NameSpell { get; set; }
        public string Student_Sex { get; set; }
        public string Student_IdentityNumber { get; set; }
        public string Student_State { get; set; }
        public string Student_Exam { get; set; }
        public string Student_Education { get; set; }
        public string Student_Specialty { get; set; }
        public string Student_Schoolofgraduation { get; set; }
        public string Student_PersonalTel { get; set; }
        public string Student_FamilyTel { get; set; }
        public string Student_QQ { get; set; }
        public string Student_Address { get; set; }
        public string Student_PostCode { get; set; }
        public string Student_EducationMoney { get; set; }
        public string Student_SkillTrainingMoney { get; set; }
        public string Student_TrainResideMoney { get; set; }
        public string Student_Evaluate1 { get; set; }
        public string Student_Evaluate2 { get; set; }
        public string Student_Remark { get; set; }
        public Nullable<int> Station_ID { get; set; }
        public Nullable<byte> Stationt_SelectStationCount { get; set; }
    
        public virtual SchoolClasses SchoolClasses { get; set; }
        public virtual Stations Stations { get; set; }
        public virtual TrainClassStudents TrainClassStudents { get; set; }
    }
}
